export const data = [
  {
    id: "1",
    nome: "Associação Nacional de Atletas (ANA)",
    segmentos: [
      {
        id: "1",
        nome: "Corrida",
        marcas: [
          {
            id: "5",
            nome: "Nike Run",
            desconto: "20%",
            preco: "R$ 599,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "6",
            nome: "Adidas Speed",
            desconto: "12%",
            preco: "R$ 499,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "7",
            nome: "Asics Gel",
            desconto: "18%",
            preco: "R$ 549,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "8",
            nome: "New Balance Fresh",
            desconto: "10%",
            preco: "R$ 479,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
        ],
      },
      {
        id: "2",
        nome: "Treino",
        marcas: [
          {
            id: "9",
            nome: "Reebok Nano",
            desconto: "8%",
            preco: "R$ 449,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "10",
            nome: "Puma Ignite",
            desconto: "15%",
            preco: "R$ 399,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "11",
            nome: "Under Armour Train",
            desconto: "10%",
            preco: "R$ 519,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "12",
            nome: "Skechers Go Train",
            desconto: "18%",
            preco: "R$ 359,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "13",
            nome: "Mizuno Wave",
            desconto: "12%",
            preco: "R$ 499,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
        ],
      },
      {
        id: "3",
        nome: "Casual",
        marcas: [
          {
            id: "14",
            nome: "Vans Classic",
            desconto: "12%",
            preco: "R$ 299,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "15",
            nome: "Converse All Star",
            desconto: "5%",
            preco: "R$ 279,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "16",
            nome: "Fila Heritage",
            desconto: "10%",
            preco: "R$ 329,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "17",
            nome: "Oakley Lifestyle",
            desconto: "8%",
            preco: "R$ 399,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
        ],
      },
    ],
  },
  {
    id: "2",
    nome: "Federação de Tênis Esportivo (FTE)",
    segmentos: [
      {
        id: "1",
        nome: "Tênis de Quadra",
        marcas: [
          {
            id: "18",
            nome: "Nike Court",
            desconto: "10%",
            preco: "R$ 599,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "19",
            nome: "Adidas Barricade",
            desconto: "15%",
            preco: "R$ 649,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "20",
            nome: "Asics Court FF",
            desconto: "8%",
            preco: "R$ 729,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "21",
            nome: "Babolat Propulse",
            desconto: "12%",
            preco: "R$ 599,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "22",
            nome: "Head Sprint",
            desconto: "5%",
            preco: "R$ 559,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
        ],
      },
      {
        id: "2",
        nome: "Corrida",
        marcas: [
          {
            id: "23",
            nome: "On Running Cloud",
            desconto: "15%",
            preco: "R$ 849,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "24",
            nome: "Saucony Triumph",
            desconto: "18%",
            preco: "R$ 799,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "25",
            nome: "Brooks Ghost",
            desconto: "12%",
            preco: "R$ 699,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "26",
            nome: "Hoka One One Clifton",
            desconto: "8%",
            preco: "R$ 749,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "27",
            nome: "Topo Athletic UltraFly",
            desconto: "10%",
            preco: "R$ 729,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
        ],
      },
      {
        id: "3",
        nome: "Casual",
        marcas: [
          {
            id: "28",
            nome: "Puma Suede",
            desconto: "10%",
            preco: "R$ 299,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "29",
            nome: "Adidas Superstar",
            desconto: "20%",
            preco: "R$ 349,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "30",
            nome: "Converse Chuck 70",
            desconto: "12%",
            preco: "R$ 399,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "31",
            nome: "New Balance 574",
            desconto: "15%",
            preco: "R$ 459,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
        ],
      },
    ],
  },
  {
    id: "3",
    nome: "Associação Nacional de Maratonistas (ANM)",
    segmentos: [
      {
        id: "1",
        nome: "Corrida de Rua",
        marcas: [
          {
            id: "32",
            nome: "Nike ZoomX",
            desconto: "20%",
            preco: "R$ 899,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "33",
            nome: "Adidas Ultraboost",
            desconto: "10%",
            preco: "R$ 799,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "34",
            nome: "Brooks Adrenaline",
            desconto: "12%",
            preco: "R$ 729,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
          {
            id: "35",
            nome: "Hoka Carbon X",
            desconto: "8%",
            preco: "R$ 899,90",
            imgUrl: "https://imgnike-a.akamaihd.net/360x360/02831251A2.jpg",
          },
        ],
      },
    ],
  },
];
